name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build server
        run: |
          nix build --print-build-logs
          # tiny smoke test
          ./result/bin/log4shell-tools-server -h
