name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@de22e16c4711fca50c816cc9081563429d1cf563
        with:
          diagnostic-endpoint:
      - name: Build server
        run: |
          nix build --print-build-logs
          # tiny smoke test
          ./result/bin/log4shell-tools-server -h
